// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpyySnGxj5rzyXNE9Ks6qJvvQl3Aac3kY',
    appId: '1:461468564546:web:b1e21fd85de2cb460081db',
    messagingSenderId: '461468564546',
    projectId: 'stylishecommerce',
    authDomain: 'stylishecommerce.firebaseapp.com',
    storageBucket: 'stylishecommerce.appspot.com',
    measurementId: 'G-88FC3MCXP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRhjD9JqVgUqtIBZGkBL1QQNj7rHbji18',
    appId: '1:461468564546:android:81a54affeb8a89960081db',
    messagingSenderId: '461468564546',
    projectId: 'stylishecommerce',
    storageBucket: 'stylishecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZO6UKXgnv9TTMXBvoW46NaRXaVbH65K0',
    appId: '1:461468564546:ios:0123424e8f9e7fb10081db',
    messagingSenderId: '461468564546',
    projectId: 'stylishecommerce',
    storageBucket: 'stylishecommerce.appspot.com',
    iosBundleId: 'com.example.stylishFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZO6UKXgnv9TTMXBvoW46NaRXaVbH65K0',
    appId: '1:461468564546:ios:0123424e8f9e7fb10081db',
    messagingSenderId: '461468564546',
    projectId: 'stylishecommerce',
    storageBucket: 'stylishecommerce.appspot.com',
    iosBundleId: 'com.example.stylishFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpyySnGxj5rzyXNE9Ks6qJvvQl3Aac3kY',
    appId: '1:461468564546:web:600217c2cf28ce890081db',
    messagingSenderId: '461468564546',
    projectId: 'stylishecommerce',
    authDomain: 'stylishecommerce.firebaseapp.com',
    storageBucket: 'stylishecommerce.appspot.com',
    measurementId: 'G-KWJBQ9S7KP',
  );
}
